# Generated by Django 5.0.6 on 2024-10-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="astronomyshow",
            old_name="theme",
            new_name="show_theme",
        ),
    ]
